version: '3.8'
services:
  fermem-web-dev:
    build: .
    profiles:
      - dev
    ports:
      - "3000:3000"
    restart: "on-failure"
  
  fermem-web-prod:
    image: javimosch/fermem-web:1
    profiles:
      - prod
    ports:
      - "3000:3000"
    restart: "on-failure"